In [2]:
import pandas as pd
import numpy as np
df = pd.read_excel('Absenteeism_at_work_Project.xlsx')
df['Body mass index'] = df.apply(
    lambda row: (row['Weight']/((row['Height']/100)*(row['Height']/100))) if np.isnan(row['Body mass index']) else row['Body mass index'],
    axis=1
    
)
df['Body mass index']=round(df['Body mass index'])

In [3]:
df['Height'] = df.apply(
    lambda row: np.sqrt(row['Weight']*10000/row['Body mass index']) if np.isnan(row['Height']) else row['Height'],
    axis=1
    
)
df['Height']=round(df['Height'])

In [4]:
df['Weight'] = df.apply(
    lambda row: (row['Body mass index']*((row['Height']/100)*(row['Height']/100))) if np.isnan(row['Weight']) else row['Weight'],
    axis=1
    
)
df['Weight']=round(df['Weight'])

In [5]:
df['Social drinker'] = df['Social drinker'].fillna(df.groupby('ID')['Social drinker'].transform('first'))
df['Social smoker'] = df['Social smoker'].fillna(df.groupby('ID')['Social smoker'].transform('first'))
df['Pet'] = df['Pet'].fillna(df.groupby('ID')['Pet'].transform('first'))
df['Son'] = df['Son'].fillna(df.groupby('ID')['Son'].transform('first'))
df['Education'] = df['Education'].fillna(df.groupby('ID')['Education'].transform('first'))
df['Disciplinary failure'] = df['Disciplinary failure'].fillna(df.groupby('ID')['Disciplinary failure'].transform('first'))
df['Work load Average/day '] = df['Work load Average/day '].fillna(df.groupby('ID')['Work load Average/day '].transform('first'))
df['Age'] = df['Age'].fillna(df.groupby('ID')['Age'].transform('first'))
df['Service time'] = df['Service time'].fillna(df.groupby('ID')['Service time'].transform('first'))
df['Distance from Residence to Work'] = df['Distance from Residence to Work'].fillna(df.groupby('ID')['Distance from Residence to Work'].transform('first'))
df['Transportation expense'] = df['Transportation expense'].fillna(df.groupby('ID')['Transportation expense'].transform('first'))
df['Height'] = df['Height'].fillna(df.groupby('ID')['Height'].transform('first'))
df['Body mass index'] = df['Body mass index'].fillna(df.groupby('ID')['Body mass index'].transform('first'))

In [6]:
df["Hit target"].fillna( method ='ffill', inplace = True)
df["Month of absence"].fillna( method ='ffill', inplace = True)

In [7]:
for column in ['Reason for absence', 'Absenteeism time in hours',]:
    df[column].fillna(df[column].mode()[0], inplace=True)

In [8]:
for column in ['Seasons', 'Day of the week','Hit target','Month of absence','Reason for absence', 'Absenteeism time in hours','Social drinker','Social smoker','Pet','Son','Education','Disciplinary failure','Work load Average/day ','Age','Service time','Distance from Residence to Work','Transportation expense','Weight','Height','Body mass index']:    
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1    #IQR is interquartile range. 

    filter = (df[column] >= Q1 - 1.5 * IQR) & (df[column] <= Q3 + 1.5 *IQR)
    df.loc[filter]

In [9]:
from scipy.stats import zscore

for column in [ 'Hit target', 'Work load Average/day ','Age','Service time','Distance from Residence to Work','Transportation expense']:        
 

# Calculate the zscores and drop zscores into new column
    df[column] = zscore(df[column])

    display(df)

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26.0,7.0,3,1,289.0,36.0,13.0,33.0,239554.0,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,4.0
1,36,0.0,7.0,3,1,118.0,13.0,18.0,50.0,239554.0,...,1.0,1.0,1.0,1.0,0.0,0.0,98.0,178.0,31.0,0.0
2,3,23.0,7.0,4,1,179.0,51.0,18.0,38.0,239554.0,...,0.0,1.0,0.0,1.0,0.0,0.0,89.0,170.0,31.0,2.0
3,7,7.0,7.0,5,1,279.0,5.0,14.0,39.0,239554.0,...,0.0,1.0,2.0,1.0,1.0,0.0,68.0,168.0,24.0,4.0
4,11,23.0,7.0,5,1,289.0,36.0,13.0,33.0,239554.0,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14.0,7.0,3,1,289.0,36.0,13.0,33.0,264604.0,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,8.0
736,1,11.0,7.0,3,1,235.0,11.0,14.0,37.0,264604.0,...,0.0,3.0,1.0,0.0,0.0,1.0,88.0,172.0,29.0,4.0
737,4,0.0,0.0,3,1,118.0,14.0,13.0,40.0,271219.0,...,0.0,1.0,1.0,1.0,0.0,8.0,98.0,170.0,34.0,0.0
738,8,0.0,0.0,4,2,231.0,35.0,14.0,39.0,271219.0,...,0.0,1.0,2.0,1.0,0.0,2.0,100.0,170.0,35.0,0.0
739,35,0.0,0.0,6,3,179.0,45.0,14.0,53.0,271219.0,...,0.0,1.0,1.0,0.0,0.0,1.0,77.0,175.0,25.0,0.0

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26.0,7.0,3,1,289.0,36.0,13.0,33.0,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,4.0
1,36,0.0,7.0,3,1,118.0,13.0,18.0,50.0,-0.803551,...,1.0,1.0,1.0,1.0,0.0,0.0,98.0,178.0,31.0,0.0
2,3,23.0,7.0,4,1,179.0,51.0,18.0,38.0,-0.803551,...,0.0,1.0,0.0,1.0,0.0,0.0,89.0,170.0,31.0,2.0
3,7,7.0,7.0,5,1,279.0,5.0,14.0,39.0,-0.803551,...,0.0,1.0,2.0,1.0,1.0,0.0,68.0,168.0,24.0,4.0
4,11,23.0,7.0,5,1,289.0,36.0,13.0,33.0,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14.0,7.0,3,1,289.0,36.0,13.0,33.0,-0.158813,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,8.0
736,1,11.0,7.0,3,1,235.0,11.0,14.0,37.0,-0.158813,...,0.0,3.0,1.0,0.0,0.0,1.0,88.0,172.0,29.0,4.0
737,4,0.0,0.0,3,1,118.0,14.0,13.0,40.0,0.011444,...,0.0,1.0,1.0,1.0,0.0,8.0,98.0,170.0,34.0,0.0
738,8,0.0,0.0,4,2,231.0,35.0,14.0,39.0,0.011444,...,0.0,1.0,2.0,1.0,0.0,2.0,100.0,170.0,35.0,0.0
739,35,0.0,0.0,6,3,179.0,45.0,14.0,53.0,0.011444,...,0.0,1.0,1.0,0.0,0.0,1.0,77.0,175.0,25.0,0.0

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26.0,7.0,3,1,289.0,36.0,13.0,-0.532868,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,4.0
1,36,0.0,7.0,3,1,118.0,13.0,18.0,2.092860,-0.803551,...,1.0,1.0,1.0,1.0,0.0,0.0,98.0,178.0,31.0,0.0
2,3,23.0,7.0,4,1,179.0,51.0,18.0,0.239405,-0.803551,...,0.0,1.0,0.0,1.0,0.0,0.0,89.0,170.0,31.0,2.0
3,7,7.0,7.0,5,1,279.0,5.0,14.0,0.393859,-0.803551,...,0.0,1.0,2.0,1.0,1.0,0.0,68.0,168.0,24.0,4.0
4,11,23.0,7.0,5,1,289.0,36.0,13.0,-0.532868,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14.0,7.0,3,1,289.0,36.0,13.0,-0.532868,-0.158813,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,8.0
736,1,11.0,7.0,3,1,235.0,11.0,14.0,0.084950,-0.158813,...,0.0,3.0,1.0,0.0,0.0,1.0,88.0,172.0,29.0,4.0
737,4,0.0,0.0,3,1,118.0,14.0,13.0,0.548314,0.011444,...,0.0,1.0,1.0,1.0,0.0,8.0,98.0,170.0,34.0,0.0
738,8,0.0,0.0,4,2,231.0,35.0,14.0,0.393859,0.011444,...,0.0,1.0,2.0,1.0,0.0,2.0,100.0,170.0,35.0,0.0
739,35,0.0,0.0,6,3,179.0,45.0,14.0,2.556224,0.011444,...,0.0,1.0,1.0,0.0,0.0,1.0,77.0,175.0,25.0,0.0

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26.0,7.0,3,1,289.0,36.0,0.101770,-0.532868,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,4.0
1,36,0.0,7.0,3,1,118.0,13.0,1.242825,2.092860,-0.803551,...,1.0,1.0,1.0,1.0,0.0,0.0,98.0,178.0,31.0,0.0
2,3,23.0,7.0,4,1,179.0,51.0,1.242825,0.239405,-0.803551,...,0.0,1.0,0.0,1.0,0.0,0.0,89.0,170.0,31.0,2.0
3,7,7.0,7.0,5,1,279.0,5.0,0.329981,0.393859,-0.803551,...,0.0,1.0,2.0,1.0,1.0,0.0,68.0,168.0,24.0,4.0
4,11,23.0,7.0,5,1,289.0,36.0,0.101770,-0.532868,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14.0,7.0,3,1,289.0,36.0,0.101770,-0.532868,-0.158813,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,8.0
736,1,11.0,7.0,3,1,235.0,11.0,0.329981,0.084950,-0.158813,...,0.0,3.0,1.0,0.0,0.0,1.0,88.0,172.0,29.0,4.0
737,4,0.0,0.0,3,1,118.0,14.0,0.101770,0.548314,0.011444,...,0.0,1.0,1.0,1.0,0.0,8.0,98.0,170.0,34.0,0.0
738,8,0.0,0.0,4,2,231.0,35.0,0.329981,0.393859,0.011444,...,0.0,1.0,2.0,1.0,0.0,2.0,100.0,170.0,35.0,0.0
739,35,0.0,0.0,6,3,179.0,45.0,0.329981,2.556224,0.011444,...,0.0,1.0,1.0,0.0,0.0,1.0,77.0,175.0,25.0,0.0

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26.0,7.0,3,1,289.0,0.429556,0.101770,-0.532868,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,4.0
1,36,0.0,7.0,3,1,118.0,-1.121694,1.242825,2.092860,-0.803551,...,1.0,1.0,1.0,1.0,0.0,0.0,98.0,178.0,31.0,0.0
2,3,23.0,7.0,4,1,179.0,1.441240,1.242825,0.239405,-0.803551,...,0.0,1.0,0.0,1.0,0.0,0.0,89.0,170.0,31.0,2.0
3,7,7.0,7.0,5,1,279.0,-1.661258,0.329981,0.393859,-0.803551,...,0.0,1.0,2.0,1.0,1.0,0.0,68.0,168.0,24.0,4.0
4,11,23.0,7.0,5,1,289.0,0.429556,0.101770,-0.532868,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14.0,7.0,3,1,289.0,0.429556,0.101770,-0.532868,-0.158813,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,8.0
736,1,11.0,7.0,3,1,235.0,-1.256585,0.329981,0.084950,-0.158813,...,0.0,3.0,1.0,0.0,0.0,1.0,88.0,172.0,29.0,4.0
737,4,0.0,0.0,3,1,118.0,-1.054248,0.101770,0.548314,0.011444,...,0.0,1.0,1.0,1.0,0.0,8.0,98.0,170.0,34.0,0.0
738,8,0.0,0.0,4,2,231.0,0.362110,0.329981,0.393859,0.011444,...,0.0,1.0,2.0,1.0,0.0,2.0,100.0,170.0,35.0,0.0
739,35,0.0,0.0,6,3,179.0,1.036566,0.329981,2.556224,0.011444,...,0.0,1.0,1.0,0.0,0.0,1.0,77.0,175.0,25.0,0.0

,ID,Reason for absence,Month of absence,Day of the week,Seasons,Transportation expense,Distance from Residence to Work,Service time,Age,Work load Average/day,...,Disciplinary failure,Education,Son,Social drinker,Social smoker,Pet,Weight,Height,Body mass index,Absenteeism time in hours
0,11,26.0,7.0,3,1,1.011408,0.429556,0.101770,-0.532868,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,4.0
1,36,0.0,7.0,3,1,-1.544379,-1.121694,1.242825,2.092860,-0.803551,...,1.0,1.0,1.0,1.0,0.0,0.0,98.0,178.0,31.0,0.0
2,3,23.0,7.0,4,1,-0.632665,1.441240,1.242825,0.239405,-0.803551,...,0.0,1.0,0.0,1.0,0.0,0.0,89.0,170.0,31.0,2.0
3,7,7.0,7.0,5,1,0.861947,-1.661258,0.329981,0.393859,-0.803551,...,0.0,1.0,2.0,1.0,1.0,0.0,68.0,168.0,24.0,4.0
4,11,23.0,7.0,5,1,1.011408,0.429556,0.101770,-0.532868,-0.803551,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735,11,14.0,7.0,3,1,1.011408,0.429556,0.101770,-0.532868,-0.158813,...,0.0,1.0,2.0,1.0,0.0,1.0,90.0,172.0,30.0,8.0
736,1,11.0,7.0,3,1,0.204318,-1.256585,0.329981,0.084950,-0.158813,...,0.0,3.0,1.0,0.0,0.0,1.0,88.0,172.0,29.0,4.0
737,4,0.0,0.0,3,1,-1.544379,-1.054248,0.101770,0.548314,0.011444,...,0.0,1.0,1.0,1.0,0.0,8.0,98.0,170.0,34.0,0.0
738,8,0.0,0.0,4,2,0.144533,0.362110,0.329981,0.393859,0.011444,...,0.0,1.0,2.0,1.0,0.0,2.0,100.0,170.0,35.0,0.0
739,35,0.0,0.0,6,3,-0.632665,1.036566,0.329981,2.556224,0.011444,...,0.0,1.0,1.0,0.0,0.0,1.0,77.0,175.0,25.0,0.0

In [10]:
df["cluster"]=np.floor(df['Absenteeism time in hours']/24)
pd.concat([df["cluster"], df['Absenteeism time in hours']], axis=1)

     cluster  Absenteeism time in hours
0        0.0                        4.0
1        0.0                        0.0
2        0.0                        2.0
3        0.0                        4.0
4        0.0                        2.0
..       ...                        ...
735      0.0                        8.0
736      0.0                        4.0
737      0.0                        0.0
738      0.0                        0.0
739      0.0                        0.0

[740 rows x 2 columns]

In [11]:
from sklearn.utils import shuffle
data =shuffle(df)
l80=int(len(df)*.8)
train_data = data[:l80]
test_data = data[l80:]

In [12]:
import scipy.spatial
from collections import Counter
class KNN:
    def __init__(self, k):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def distance(self, X1, X2):
        distance = scipy.spatial.distance.euclidean(X1, X2)

    def predict(self, X_test):
        final_output = []
        for i in range(len(X_test)):
            d = []
            votes = []
            for j in range(len(X_train)):
                dist = scipy.spatial.distance.euclidean(X_train[j] , X_test[i])
                d.append([dist, j])
            d.sort()
            d = d[0:self.k]
            for d, j in d:
                votes.append(y_train[j])
            ans = Counter(votes).most_common(1)[0][0]
            final_output.append(ans)

        return final_output

    def score(self, X_test, y_test):
        predictions = self.predict(X_test)
        return (predictions == y_test).sum() / len(y_test)

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import auc
import matplotlib.pyplot as plt
import seaborn as sns

 
y = df["cluster"].values
x = df.drop(["cluster",'Absenteeism time in hours'], axis = 1)
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x = ss.fit_transform(x)

#SPlitting into train and test
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.5)
# Create feature and target arrays

train_score = []
test_score = []
k_vals = []

for k in range(1, 21):
    k_vals.append(k)
    knn = KNeighborsClassifier(n_neighbors = k)
   
    knn.fit(X_train, y_train)
    
    tr_score = knn.score(X_train, y_train)
    train_score.append(tr_score)
    
    te_score = knn.score(X_test, y_test)
    test_score.append(te_score)
#Scaling - mandatory for knn


max_test_score = max(test_score)
test_scores_ind = [i for i, v in enumerate(test_score) if v == max_test_score]
print('Max test score {} and k = {}'.format(max_test_score * 100, list(map(lambda x: x + 1, test_scores_ind))))
knn = KNeighborsClassifier(3)

knn.fit(X_train, y_train)
knn.score(X_test, y_test)
y_pred = knn.predict(X_test)
confusion_matrix(y_test,y_pred)
pd.crosstab(y_test, y_pred, rownames = ['Actual'], colnames =['Predicted'], margins = True)
print(classification_report(y_test, y_pred))
clf = KNN(3)
clf.fit(X_train, y_train)
prediction = clf.predict(X_test)


prediction == y_test

clf.score(X_test, y_test)

Max test score 94.32432432432432 and k = [5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

D:\file\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\file\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\file\anacoda\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

         0.0       0.95      0.99      0.97       349
         1.0       0.00      0.00      0.00        13
         2.0       0.00      0.00      0.00         4
         3.0       0.00      0.00      0.00         2
         4.0       0.00      0.00      0.00         1
         5.0       0.00      0.00      0.00         1

    accuracy                           0.94       370
   macro avg       0.16      0.17      0.16       370
weighted avg       0.89      0.94      0.91       370

0.9378378378378378

برای اجرای الگوریتم 
knn
باید همه ی ستون ها یا به صورت پیوسته باشند یا گسسته.اگر ستونی شامل هر دو نوع بود باید تابعی ایجاد کرد که مقادیر با عددی 
(numerical)
کند و سپس الگوریتم را روی آن اعمال کرد

اگر بعد کم باشد با شرط کم بودن بعد میتوان الگوریتم 
knn 
را پیاده سازی کرد. ولی اگر بعد زیاد باشد الگوریتم دچار نفرین بعد میشود پس ناچارا با اجرای الگوریتم های کاهش بعد مثل پی سی ای میتوانیم این مشکل را رفع کنیم

In [14]:

from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression 
 
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[343   3   1   0   1   1]
 [ 12   1   0   0   0   0]
 [  4   0   0   0   0   0]
 [  2   0   0   0   0   0]
 [  1   0   0   0   0   0]
 [  1   0   0   0   0   0]]

In [15]:
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
pca = PCA(n_components = 11)
 
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
clf = KNN(3)
clf.fit(X_train, y_train)
prediction = clf.predict(X_test)


prediction == y_test

clf.score(X_test, y_test)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,  prediction))

[[343   3   1   0   1   1]
 [ 12   1   0   0   0   0]
 [  4   0   0   0   0   0]
 [  2   0   0   0   0   0]
 [  1   0   0   0   0   0]
 [  1   0   0   0   0   0]]
0.9378378378378378

In [16]:

import matplotlib.pyplot as plt 
from matplotlib.colors import ListedColormap
X_set, y_set = x_test, y_test
#X_set=x_set[:,2]
print(X_set.shape)
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1,
                     stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1,
                     stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf((X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X2.shape)), alpha = 0.75,
             cmap = ListedColormap(('yellow', 'white', 'aquamarine')))
 
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
 
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green', 'blue'))(i), label = j)
 
# title for scatter plot
plt.title('Logistic Regression (Test set)')
plt.xlabel('PC1') # for Xlabel
plt.ylabel('PC2') # for Ylabel
plt.legend()
 
# show scatter plot
plt.show()

NameError: name 'x_test' is not defined